version: "3"

services:
  # DISCOVERY SERVICE
  discovery:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    environment:
      - DISCOVERY_URL=http://discovery:8761

  # SERVICES
  articles:
    build:
      context: ./article-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  articles_two:
    build:
      context: ./article-service
      dockerfile: Dockerfile
    ports:
      - 9080:8080
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  authors:
    build:
      context: ./author-service
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  authors_two:
    build:
      context: ./author-service
      dockerfile: Dockerfile
    ports:
      - 9081:8081
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
    depends_on:
      - discovery

  # API GATEWAY
  gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - 8765:8765
    environment:
      - DISCOVERY_URL=http://discovery:8761
    links:
      - discovery
      - authors
      - authors_two
      - articles
      - articles_two
    depends_on:
      - discovery